ENH: Allow setting device to mps for m3 acceleration
WIP: Add support functions needed for conditional type

MPS does not support tensors are 64 bit floats.

WIP: temporary changes to help diagnose use of 64bit floats with mps.

WIP: Rough test to get first batch of tests passing with mps

This approach is likely overly simplistic, and may affect
cpu computation precision on GPU implementations.  It is intended
to spark initial conversations.

WIP: fix floating point precison matches.

WIP: Minor formatting fixes to

ENH: Allow setting device to mps for m3 acceleration

BUG: Test failure when NGC_ORG environ not set

```txt
  File "MONAI/monai/bundle/scripts.py", line 541, in download
    raise ValueError(f"repo should be in the form of `org/org_name/team/team_name` or `org/org_name`, got {repo_}.")
ValueError: repo should be in the form of `org/org_name/team/team_name` or `org/org_name`, got Project-MONAI/model-zoo/hosting_storage_v1.
```

Disable this test that requires special access permissions to accomplish the download.

DOC: Provide improved test failure diagnostics

After running the test suite, the summary results
and the failing tests should be easy to identify.

WIP: Need to break apart and commit separate supports