BUG: Test failure when NGC_ORG environ not set
```txt
  File "MONAI/monai/bundle/scripts.py", line 541, in download
    raise ValueError(f"repo should be in the form of `org/org_name/team/team_name` or `org/org_name`, got {repo_}.")
ValueError: repo should be in the form of `org/org_name/team/team_name` or `org/org_name`, got Project-MONAI/model-zoo/hosting_storage_v1.
```

Disable this test that requires special access permissions to accomplish the download.